# fail_fast: true
repos:
  # - repo: local
  #   hooks:
  #     - id: run-version-update
  #       name: "version-update"
  #       entry: python scripts/update_version.py
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
  #       stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
        exclude: 'frontend/src/locales/(en|es)\.json'
        stages: [pre-commit]
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
          - "--unsafe"
        stages: [pre-commit]
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.14
        stages: [pre-commit]
        args: ["--line-length=120"]
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        stages: [pre-commit]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
      - id: poetry-check
        stages: [pre-commit]
        args: ["-C", "./fastapi"]
      - id: poetry-lock
        stages: [pre-commit]
        args: ["-C", "./fastapi"]
      - id: poetry-export
        args: ["-C", "./fastapi", "-f", "requirements.txt", "-o", "requirements.txt"]
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: run-tests
        name: "Run tests"
        entry: poetry -C fastapi run pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
