version: '3'

services:
  db:
    image: postgres:10
    container_name: auth_db_postgres
    environment:
      POSTGRES_DB: Fausto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: faustoauthdb24$$ # solo con un dolar $
    ports:
      - "5464:5432"
    volumes:
      - ./docker/postgres_db/initdb/:/docker-entrypoint-initdb.d
      - ./data_temp/pgdb/backup:/pgdb/backup
      - ./data_temp/pgdb/script:/pgdb/script
  db_admin:
    build:
      context: .
      dockerfile: ./docker/pgadmin/Dockerfile
    container_name: auth_db_admin_postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fausto.app
      PGADMIN_DEFAULT_PASSWORD: admin24$$ # solo con un dolar $
    ports:
      - "8081:80"
    volumes:
      - ./data_temp/pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/data.json:/pgadmin4/servers.json
    # logging:
    #   driver: none
  redis:
    image: redis
    container_name: auth_cache
    expose:
      - 6379
    depends_on:
      - api
  api:
    image: richard24se/api_faustoauth
    restart: always
  api_nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/nginx.Dockerfile
      args:
        hostname_app: api
        port_app: 5000
    ports:
      - "5111:5000"
    restart: always

